default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>

test:
  <<: *default
  database: budget_app_test
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>

production:
  <<: *default
  database: budget_app_production
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>
